### ISSUE TITLE
There is no way to bring back Mario after he dies

### ISSUE THREAD

**Issue by UrkiMimi** [ckosmic/SM64BS#2]
I was messing around with this and found out you can die in this mod and dying in this mod soft locks Mario.
![image](https://user-images.githubusercontent.com/74517821/158259785-d79ddeeb-527c-4e64-9974-e0adcfb9c8e3.png)
Could you try fixing this and thanks in advance. ❤

**Comment by FlipsSimple** [comment]
which headset are you using

**Comment by UrkiMimi** [comment]
Rift CV1 but I doubt it matters since the same issue happens with https://github.com/libsm64/libsm64-blender

**Comment by FlipsSimple** [comment]
is there any way to use this on quest 2 or

**Comment by UrkiMimi** [comment]
bruh
