### ISSUE TITLE
Mario crashes other mods after world position overflow

### ISSUE THREAD

**Issue by shrdyfrdy** [ckosmic/SM64BS#3]
Unfortunely I have a little driftstick on my controller so my mario is slowly going behind me, after playing some maps I've noiticed that somehow got himself out of walkable "boundary" and then when I played one more map, game UI crashed. After restarting the game mario haven't been seen anywhere, and some mods like Counters+ weren't working. You can reproduce the bug by changing the Mario position in USERDATA config file to:
x: 100000.999
y: 100000.999
z: 100000.999

After changing position to "normal" state, everything seems to work same as before.

Here's what I've seen in logs:
[CRITICAL @ 02:14:15 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 02:14:15 | UnityEngine] SM64BS.Managers.MenuMarioManager.Initialize () (at <8941466c57614d7986770d011ba51d06>:0)
[CRITICAL @ 02:14:15 | UnityEngine] Zenject.InitializableManager.Initialize () (at <b2cc02012594432582d34a1cdfb29cd9>:0)
[CRITICAL @ 02:14:15 | UnityEngine] Rethrow as ZenjectException: Error occurred while initializing IInitializable with type 'MenuMarioManager'
[CRITICAL @ 02:14:15 | UnityEngine] Zenject.InitializableManager.Initialize () (at <b2cc02012594432582d34a1cdfb29cd9>:0)
[CRITICAL @ 02:14:15 | UnityEngine] Zenject.MonoKernel.Initialize () (at <b2cc02012594432582d34a1cdfb29cd9>:0)
[CRITICAL @ 02:14:15 | UnityEngine] Zenject.MonoKernel.Start () (at <b2cc02012594432582d34a1cdfb29cd9>:0)

**Comment by ckosmic** [comment]
Thanks, this has been fixed in 0cf1843 and [03c7b96](https://github.com/ckosmic/libsm64/commit/03c7b9632b117dbfbe4ece21e32832669ffe3b92)
